CFLAGS = -std=gnu11 -Wall -Wextra -lm -fopenmp -O3
CC = gcc-14

.PHONY: all
all: snippet1 snippet2 snippet3

.PHONY: clean
clean:
	$(RM) snippet1 snippet2 snippet3


snippet1: snippet1.c


snippet2: snippet2.c


snippet3: snippet3.c







